CREATE TABLE IF NOT EXISTS ratings (
    mid VARCHAR(36) PRIMARY KEY,
    sum_of_votes BIGINT NOT NULL DEFAULT 0,
    total_votes INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (mid) REFERENCES movies(mid) ON DELETE CASCADE
);
